import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";

import { Theme, ThemePanel } from "@radix-ui/themes";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body suppressHydrationWarning={true} className={inter.className}>
        <Theme accentColor="blue" grayColor="gray" radius="large">
          <AuthProvider>
            <QueryClientProvider>
              <NavBar />
              <main className="px-4">{children}</main>
            </QueryClientProvider>
          </AuthProvider>
          {/* <ThemePanel /> */}
        </Theme>
      </body>
    </html>
  );
}
