import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="emerald" lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <AuthProvider>
          <QueryClientProvider>
            <NavBar />
            <main className="px-4">{children}</main>
          </QueryClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
